- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t takawat/goapp:latest .
    args:
     chdir: /opt/docker

  - name: create tag to push image onto dockerhub
    command: docker tag goapp takawat/goapp:latest

  - name: push docker image
    command: docker push takawat/goapp:latest
