apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"goapp"},"name":"takawat-goapp","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"goapp"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"goapp"}},"spec":{"containers":[{"image":"takawat/goapp","imagePullPolicy":"Always","name":"goapp","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2025-04-01T02:02:40Z"
  generation: 2
  labels:
    app: goapp
  name: takawat-goapp
  namespace: default
  resourceVersion: "13993"
  uid: c93db88c-4ef8-414f-a832-3af111f7299e
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: goapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-04-01T02:02:42Z"
      creationTimestamp: null
      labels:
        app: goapp
    spec:
      containers:
      - image: takawat/goapp
        imagePullPolicy: Always
        name: goapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-04-01T02:02:40Z"
    lastUpdateTime: "2025-04-01T02:02:40Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-04-01T02:02:40Z"
    lastUpdateTime: "2025-04-01T02:02:42Z"
    message: ReplicaSet "takawat-goapp-5b7d56b76" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 2