apiVersion: v1
kind: Service
metadata:
  name: takawat-service
  namespace: default
  labels:
    app: goapp
spec:
  type: LoadBalancer  # Use "NodePort" if not on a cloud provider
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 8080      # External Port
      targetPort: 8080 # Pod Port